services:
  meshmonitor:
    # Option 1: Use pre-built image from GitHub Container Registry (recommended)
    image: ghcr.io/yeraze/meshmonitor:latest

    # Option 2: Build locally (comment out 'image' above and uncomment below for development)
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    container_name: meshmonitor
    ports:
      - "8080:3001"
    restart: unless-stopped
    volumes:
      - meshmonitor-data:/data
    env_file: .env
    environment:
      # Minimal configuration for http://localhost:8080
      - NODE_ENV=development  # Use development mode for simple HTTP deployments
      - TZ=America/New_York

      # OPTIONAL: Uncomment and configure for production deployments
      # See docs/configuration/production.md for full production setup guide

      # For production with HTTPS reverse proxy (nginx, Caddy, Traefik):
      # - NODE_ENV=production
      # - SESSION_SECRET=your-generated-secret-here  # Required in production
      # - TRUST_PROXY=true
      # - ALLOWED_ORIGINS=https://yourdomain.com

      # For production with direct HTTP (not recommended):
      # - NODE_ENV=production
      # - SESSION_SECRET=your-generated-secret-here  # Required in production
      # - COOKIE_SECURE=false

volumes:
  meshmonitor-data:
    driver: local
