services:
  meshmonitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meshmonitor-reverse-proxy-test
    ports:
      - "8084:3001"
    volumes:
      - meshmonitor-reverse-proxy-test-data:/data
    environment:
      # Production configuration for HTTPS reverse proxy
      - NODE_ENV=production
      - MESHTASTIC_NODE_IP=192.168.5.106
      - TRUST_PROXY=true
      - ALLOWED_ORIGINS=https://meshdev.yeraze.online
      - COOKIE_SECURE=true
      - COOKIE_SAMESITE=lax
      # SESSION_SECRET intentionally not set to test auto-generation
    restart: unless-stopped

volumes:
  meshmonitor-reverse-proxy-test-data:
