apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meshmonitor.fullname" . }}
  labels:
    {{- include "meshmonitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "meshmonitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "meshmonitor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: MESHTASTIC_NODE_IP
          value: {{ .Values.env.meshtasticNodeIp | quote }}
        - name: MESHTASTIC_USE_TLS
          value: {{ .Values.env.meshtasticUseTls | quote }}
        - name: NODE_ENV
          value: {{ .Values.env.nodeEnv | quote }}
        - name: PORT
          value: {{ .Values.env.port | quote }}
        {{- if .Values.env.baseUrl }}
        - name: BASE_URL
          value: {{ .Values.env.baseUrl | quote }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /data
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "meshmonitor.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
