/**
 * Network survey panel (#4726).
 *
 * Answers "what can this radio actually reach?" from data already collected —
 * no radio traffic is generated by viewing this. The copy says so explicitly,
 * because a panel called "survey" that quietly transmitted would be a nasty
 * surprise on a shared medium, and a user has no other way to tell.
 *
 * Distinguishes three states that a naive "no data" would collapse into one:
 * loading, genuinely-nothing-heard, and a query that failed. A young install
 * with an empty mesh must not look broken, and a broken one must not look
 * empty.
 */
import { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import apiService from '../../services/api';
import { UiIcon } from '../icons/UiIcon';
import { nodeLabel } from './nodeLabel';
import styles from './NetworkSurveyPanel.module.css';

export interface DirectNeighbour {
  nodeNum: number;
  name: string | null;
  avgRssi: number | null;
  packetCount: number;
  lastHeard: number;
}

export interface NetworkSurvey {
  sourceId: string;
  generatedAt: number;
  windowHours: number;
  nodes: { total: number; activeInWindow: number; withPosition: number };
  directNeighbours: DirectNeighbour[];
  hopDistribution: Array<{ hops: number; nodeCount: number }>;
  maxHops: number | null;
}

export interface NetworkSurveyPanelProps {
  sourceId?: string | null;
  /** Window options offered to the user, in hours. */
  windowOptions?: number[];
}

const DEFAULT_WINDOWS = [1, 6, 24, 24 * 7];

export default function NetworkSurveyPanel({
  sourceId,
  windowOptions = DEFAULT_WINDOWS,
}: NetworkSurveyPanelProps) {
  const { t } = useTranslation();
  const [survey, setSurvey] = useState<NetworkSurvey | null>(null);
  const [hours, setHours] = useState(24);
  const [loading, setLoading] = useState(false);
  const [failed, setFailed] = useState(false);

  const load = useCallback(async () => {
    if (!sourceId) return;
    setLoading(true);
    setFailed(false);
    try {
      const res = await apiService.get<{ success: boolean; data: NetworkSurvey }>(
        `/sources/${sourceId}/survey?hours=${hours}`,
      );
      setSurvey(res?.data ?? null);
    } catch {
      // Distinct from "nothing heard" — see the module comment.
      setFailed(true);
    } finally {
      setLoading(false);
    }
  }, [sourceId, hours]);

  useEffect(() => { void load(); }, [load]);

  if (!sourceId) return null;

  const maxBucket = survey?.hopDistribution.reduce((m, b) => Math.max(m, b.nodeCount), 0) ?? 0;

  return (
    <section className={styles.survey} data-testid="network-survey-panel">
      <header className={styles.surveyHead}>
        <h3 className={styles.surveyTitle}>
          <UiIcon name="activity" /> {t('survey.title')}
        </h3>
        <label className={styles.surveyWindow}>
          {t('survey.window')}
          <select
            value={hours}
            disabled={loading}
            onChange={(e) => setHours(Number(e.target.value))}
            data-testid="survey-window"
          >
            {windowOptions.map((h) => (
              <option key={h} value={h}>{t('survey.window_hours', { count: h })}</option>
            ))}
          </select>
        </label>
      </header>

      {/* Stated plainly: this view costs no airtime. */}
      <p className={styles.surveyPassive}>{t('survey.passive_note')}</p>

      {failed && (
        <p className={styles.surveyError} role="alert" data-testid="survey-error">
          {t('survey.failed')}{' '}
          <button type="button" onClick={() => void load()}>{t('survey.retry')}</button>
        </p>
      )}

      {loading && !survey && <p data-testid="survey-loading">{t('survey.loading')}</p>}

      {survey && (
        <>
          <dl className={styles.surveyStats}>
            <div>
              <dt>{t('survey.nodes_total')}</dt>
              <dd data-testid="survey-total">{survey.nodes.total}</dd>
            </div>
            <div>
              <dt>{t('survey.nodes_active')}</dt>
              <dd data-testid="survey-active">{survey.nodes.activeInWindow}</dd>
            </div>
            <div>
              <dt>{t('survey.nodes_positioned')}</dt>
              <dd>{survey.nodes.withPosition}</dd>
            </div>
            <div>
              <dt>{t('survey.max_hops')}</dt>
              {/* An em dash, not 0: "no traceroute has been answered" is not
                  the same claim as "the mesh is zero hops wide". */}
              <dd data-testid="survey-maxhops">{survey.maxHops ?? '—'}</dd>
            </div>
          </dl>

          <h4>{t('survey.direct_neighbours')}</h4>
          {survey.directNeighbours.length === 0 ? (
            <p className={styles.surveyEmpty} data-testid="survey-no-neighbours">
              {t('survey.no_neighbours')}
            </p>
          ) : (
            <table className={styles.surveyTable}>
              <thead>
                <tr>
                  <th>{t('survey.node')}</th>
                  <th>{t('survey.rssi')}</th>
                  <th>{t('survey.packets')}</th>
                </tr>
              </thead>
              <tbody>
                {survey.directNeighbours.map((n) => (
                  <tr key={n.nodeNum} data-testid={`survey-neighbour-${n.nodeNum}`}>
                    <td>{nodeLabel(n)}</td>
                    <td>{n.avgRssi == null ? '—' : `${n.avgRssi} dBm`}</td>
                    <td>{n.packetCount}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}

          <h4>{t('survey.reach')}</h4>
          {survey.hopDistribution.length === 0 ? (
            <p className={styles.surveyEmpty} data-testid="survey-no-hops">{t('survey.no_hops')}</p>
          ) : (
            <ul className={styles.surveyHops}>
              {survey.hopDistribution.map((b) => (
                <li key={b.hops} data-testid={`survey-hop-${b.hops}`}>
                  <span className={styles.surveyHopLabel}>
                    {b.hops === 0 ? t('survey.hops_direct') : t('survey.hops_n', { count: b.hops })}
                  </span>
                  <span
                    className={styles.surveyHopBar}
                    style={{ width: `${maxBucket ? (b.nodeCount / maxBucket) * 100 : 0}%` }}
                  />
                  <span className={styles.surveyHopCount}>{b.nodeCount}</span>
                </li>
              ))}
            </ul>
          )}
        </>
      )}
    </section>
  );
}
