#!/bin/bash
# Welcome message displayed when the devcontainer starts

# Dynamically read version from package.json
VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "unknown")

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║              Welcome to MeshMonitor DevContainer             ║"
echo "║                        v$VERSION                             ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📡 Meshtastic Mesh Network Monitoring Platform"
echo ""
echo "Quick Start Commands:"
echo "  npm run dev:full       # Start React (5173) + Express (3001)"
echo "  npm run dev            # React dev server only"
echo "  npm run dev:server     # Express API server only"
echo ""
echo "Testing & Quality:"
echo "  npm run test           # Run tests in watch mode"
echo "  npm run test:run       # Run all tests once (required before PR)"
echo "  npm run test:coverage  # Generate coverage report"
echo "  npm run lint           # Run ESLint"
echo "  npm run typecheck      # TypeScript checks"
echo ""
echo "Docker Testing:"
echo "  docker compose -f docker-compose.dev.yml build"
echo "  docker compose -f docker-compose.dev.yml up"
echo "  # NOTE: Cannot run devcontainer + docker-compose.dev.yml simultaneously!"
echo ""
echo "Documentation:"
echo "  cat .devcontainer/README.md        # DevContainer setup & usage"
echo "  npm run docs:dev                   # Start VitePress docs server"
echo "  cat .claude/instructions.md        # AI agent instructions"
echo "  cat docs/ARCHITECTURE_LESSONS.md   # Architecture patterns"
echo "  cat CONTRIBUTING.md                # Contribution guidelines"
echo ""
echo "Claude Code CLI (AI Assistant):"
echo "  claude                             # Start Claude Code (authenticate on first run)"
echo "  # Authentication: OAuth (recommended) or API key"
echo "  # See .devcontainer/README.md for details"
echo ""
echo "Important Reminders:"
echo "  ⚠ Backend only talks to nodes (never frontend directly)"
echo "  ⚠ Test on 'gauntlet' channel, NEVER on Primary!"
echo "  ⚠ DO NOT MODIFY Catppuccin theme colors"
echo "  ⚠ Always run tests/system-tests.sh before creating PR"
echo "  ⚠ Use conventional commits (feat:, fix:, chore:, etc.)"
echo "  ⚠ Never push directly to main - use feature branches"
echo ""
echo "Ports:"
echo "  5173 → Vite Dev Server (React)"
echo "  3001 → Express API Server"
echo "  4404 → Virtual Node (Testing)"
echo "  8080 → Docker Testing Port"
echo ""
echo "Happy coding! 🚀"
echo ""
