import type { DistanceUnit } from '../contexts/SettingsContext.js';

export interface PolarGridRing {
  radiusMeters: number;
  label: string;
}

/**
 * Zoom level to ring interval in meters.
 * Each zoom maps to the interval between rings; 5 rings are generated by default.
 */
const ZOOM_INTERVALS: Record<number, number> = {
  3: 500000,   // 500km
  4: 200000,   // 200km
  5: 100000,   // 100km
  6: 50000,    // 50km
  7: 20000,    // 20km
  8: 10000,    // 10km
  9: 5000,     // 5km
  10: 5000,    // 5km
  11: 2000,    // 2km
  12: 1000,    // 1km
  13: 1000,    // 1km
  14: 500,     // 500m
  15: 200,     // 200m
  16: 100,     // 100m
  17: 50,      // 50m
  18: 20,      // 20m
};

const RING_COUNT = 5;
const METERS_PER_KM = 1000;
const METERS_PER_MILE = 1609.344;
const FEET_PER_MILE = 5280;

function formatMetricLabel(meters: number): string {
  if (meters >= METERS_PER_KM) {
    const km = meters / METERS_PER_KM;
    // Use integer if whole number, otherwise one decimal
    const value = Number.isInteger(km) ? km.toString() : km.toFixed(1).replace(/\.0$/, '');
    return `${value}km`;
  }
  return `${meters}m`;
}

function formatImperialLabel(meters: number): string {
  const miles = meters / METERS_PER_MILE;
  if (miles >= 1) {
    const value = Number.isInteger(miles) ? miles.toString() : parseFloat(miles.toFixed(1)).toString();
    return `${value}mi`;
  }
  const feet = Math.round(meters * (FEET_PER_MILE / METERS_PER_MILE));
  return `${feet}ft`;
}

/**
 * Returns polar grid rings for a given zoom level and distance unit.
 * Always returns exactly RING_COUNT rings with monotonically increasing radii.
 */
export function getPolarGridRings(zoom: number, unit: DistanceUnit): PolarGridRing[] {
  // Clamp zoom to supported range
  const clampedZoom = Math.max(3, Math.min(18, zoom));
  const interval = ZOOM_INTERVALS[clampedZoom];

  const rings: PolarGridRing[] = [];
  for (let i = 1; i <= RING_COUNT; i++) {
    const radiusMeters = interval * i;
    const label = unit === 'mi' ? formatImperialLabel(radiusMeters) : formatMetricLabel(radiusMeters);
    rings.push({ radiusMeters, label });
  }
  return rings;
}

/**
 * Given a center point, bearing (degrees from north, clockwise), and distance in meters,
 * returns the destination point using the Haversine destination formula.
 */
export function getSectorEndpoint(
  center: { lat: number; lng: number },
  bearingDeg: number,
  distanceMeters: number,
): { lat: number; lng: number } {
  const R = 6371000; // Earth's radius in meters
  const δ = distanceMeters / R; // angular distance
  const θ = (bearingDeg * Math.PI) / 180; // bearing in radians
  const φ1 = (center.lat * Math.PI) / 180;
  const λ1 = (center.lng * Math.PI) / 180;

  const φ2 = Math.asin(
    Math.sin(φ1) * Math.cos(δ) + Math.cos(φ1) * Math.sin(δ) * Math.cos(θ),
  );
  const λ2 =
    λ1 +
    Math.atan2(
      Math.sin(θ) * Math.sin(δ) * Math.cos(φ1),
      Math.cos(δ) - Math.sin(φ1) * Math.sin(φ2),
    );

  return {
    lat: (φ2 * 180) / Math.PI,
    lng: (λ2 * 180) / Math.PI,
  };
}
