/**
 * MeshCoreObserverKeyStore
 *
 * Encrypts and persists a MeshCore source's companion Ed25519 (orlp format)
 * signing key, used to mint MeshCore Analyzer Observer auth tokens (#4457).
 * Structural copy of `SourcePkiKeyStore` / `MeshCoreCredentialStore`:
 * AES-256-GCM with an HKDF-derived key from `SESSION_SECRET`, with an
 * envelope `kid` so a rotated secret is detected (`key_rotated`) rather than
 * silently failing with an auth-tag error.
 *
 * KDF info strings are deliberately NEW and distinct from both
 * `SourcePkiKeyStore` ('source-pki-key-*') and `MeshCoreCredentialStore`
 * ('meshcore-admin-creds-*') — this is the load-bearing difference from
 * those two models. Reusing an existing info string would mean a leaked
 * SESSION_SECRET plus a copy of this table could be decrypted by code that
 * only knows the *other* store's derivation, or vice versa; distinct info
 * strings key-separate the three stores even though they share one secret.
 *
 * Threat model (same as the other two stores):
 *   - Defends against a DB-file-only exfil (someone grabs `meshmonitor.db`
 *     without the host environment).
 *   - Does NOT defend against host compromise. Anyone running code on the
 *     host can read SESSION_SECRET and the DB.
 *
 * Capability gating: when SESSION_SECRET was NOT explicitly configured
 * (auto-generated by the environment loader), `canStore` is false — an
 * ephemeral key would lose the stored signing key on every restart.
 */
import crypto from 'node:crypto';
import databaseService from '../../services/database.js';
import { logger } from '../../utils/logger.js';
import { getEnvironmentConfig } from '../config/environment.js';

/** KDF version stamped into each envelope. Bump if the HKDF info-strings or
 *  AEAD parameters ever change so old rows route through key_rotated. */
const KDF_VERSION = 1;
const KDF_INFO_AEAD = 'meshcore-observer-key-aead-v1';
const KDF_INFO_FINGERPRINT = 'meshcore-observer-key-fingerprint-v1';

interface StoredEnvelope {
  v: number;
  kid: string;
  iv: string;
  ct: string;
  tag: string;
}

export interface ObserverKeyCapability {
  canStore: boolean;
  /** Human-readable explanation when canStore=false, surfaced to the UI. */
  reason?: string;
}

export type ObserverKeyLoadResult =
  | { kind: 'none' }
  | { kind: 'ok'; privateKeyHex: string; publicKeyHex: string | null; origin: 'device' | 'manual' }
  | { kind: 'key_rotated'; storedKid: string };

export interface ObserverKeyStatus {
  stored: boolean;
  /** 32-byte hex, UPPERCASE. Not secret — broadcast in every ADVERT. */
  publicKey: string | null;
  origin: 'device' | 'manual' | null;
  updatedAt: number | null;
  /** True when an envelope exists but was encrypted under a different SESSION_SECRET. */
  keyRotated: boolean;
  canStore: boolean;
  reason: string | null;
}

export class MeshCoreObserverKeyStore {
  private readonly aeadKey: Buffer;
  private readonly currentKid: string;
  private readonly _capability: ObserverKeyCapability;

  constructor(sessionSecret: string, sessionSecretProvided: boolean) {
    this._capability = sessionSecretProvided
      ? { canStore: true }
      : {
          canStore: false,
          reason:
            'SESSION_SECRET was not configured; an auto-generated value is in use. ' +
            'A stored Analyzer Observer signing key would be unrecoverable on every restart. ' +
            'Set SESSION_SECRET=$(openssl rand -hex 32) to enable the Analyzer Observer.',
        };
    const ikm = Buffer.from(sessionSecret, 'utf8');
    this.aeadKey = hkdfBytes(ikm, KDF_INFO_AEAD, 32);
    this.currentKid = hkdfBytes(ikm, KDF_INFO_FINGERPRINT, 4).toString('hex');
  }

  get capability(): ObserverKeyCapability {
    return this._capability;
  }

  /** First 8 hex chars of the HKDF fingerprint of the current SESSION_SECRET.
   *  Exposed mostly for tests; consumers should use `load()`/`status()` and
   *  react to `key_rotated`/`keyRotated` rather than comparing fingerprints. */
  get currentFingerprint(): string {
    return this.currentKid;
  }

  /**
   * Encrypt and persist `privateKeyHex` (128-char orlp private-key hex,
   * stored as UTF-8 text — consistent with `MeshCoreCredentialStore`'s
   * string handling rather than saving 64 raw bytes) for a source, alongside
   * the clear `publicKeyHex` (32-byte hex, not secret). Throws when
   * SESSION_SECRET is auto-generated — callers must check `capability` first.
   */
  async store(
    sourceId: string,
    privateKeyHex: string,
    publicKeyHex: string,
    origin: 'device' | 'manual',
  ): Promise<void> {
    if (!this._capability.canStore) {
      throw new Error('Cannot persist Analyzer Observer signing key: SESSION_SECRET is auto-generated');
    }
    const iv = crypto.randomBytes(12);
    const cipher = crypto.createCipheriv('aes-256-gcm', this.aeadKey, iv);
    const ct = Buffer.concat([cipher.update(Buffer.from(privateKeyHex, 'utf8')), cipher.final()]);
    const tag = cipher.getAuthTag();
    const envelope: StoredEnvelope = {
      v: KDF_VERSION,
      kid: this.currentKid,
      iv: iv.toString('hex'),
      ct: ct.toString('hex'),
      tag: tag.toString('hex'),
    };
    await databaseService.meshcoreObserverKeys.upsert(sourceId, JSON.stringify(envelope), publicKeyHex, origin);
  }

  /**
   * Load + decrypt the stored signing key for a source. Returns one of:
   *   - `{ kind: 'none' }` when nothing is saved.
   *   - `{ kind: 'ok', privateKeyHex, publicKeyHex, origin }` on success.
   *   - `{ kind: 'key_rotated', storedKid }` when the envelope was encrypted
   *     with a different SESSION_SECRET.
   */
  async load(sourceId: string): Promise<ObserverKeyLoadResult> {
    const row = await databaseService.meshcoreObserverKeys.getBySourceId(sourceId);
    if (!row) return { kind: 'none' };

    let env: StoredEnvelope;
    try {
      env = JSON.parse(row.encryptedPrivateKey) as StoredEnvelope;
    } catch {
      logger.warn(`[MeshCoreObserverKeyStore] Malformed key envelope for ${sourceId}; treating as rotated`);
      return { kind: 'key_rotated', storedKid: '?' };
    }
    if (env.v !== KDF_VERSION || env.kid !== this.currentKid) {
      return { kind: 'key_rotated', storedKid: env.kid ?? '?' };
    }
    try {
      const decipher = crypto.createDecipheriv('aes-256-gcm', this.aeadKey, Buffer.from(env.iv, 'hex'));
      decipher.setAuthTag(Buffer.from(env.tag, 'hex'));
      const pt = Buffer.concat([decipher.update(Buffer.from(env.ct, 'hex')), decipher.final()]);
      const origin: 'device' | 'manual' = row.keyOrigin === 'manual' ? 'manual' : 'device';
      return { kind: 'ok', privateKeyHex: pt.toString('utf8'), publicKeyHex: row.publicKey ?? null, origin };
    } catch (err) {
      // kid matched but decrypt failed. Either an upgrade hazard or row
      // corruption — treat as rotated so callers re-derive/re-store rather
      // than silently proceeding with a broken key.
      logger.warn(
        `[MeshCoreObserverKeyStore] Key decrypt failed for ${sourceId} despite matching kid: ${(err as Error).message}`,
      );
      return { kind: 'key_rotated', storedKid: env.kid };
    }
  }

  /** Clear any stored key for a source. No-op if none exists. */
  async clear(sourceId: string): Promise<void> {
    await databaseService.meshcoreObserverKeys.deleteBySourceId(sourceId);
  }

  /**
   * Report status without attempting decryption: compares the envelope's
   * `v`/`kid` against the current fingerprint only (cheap — same trick as
   * `MeshCoreCredentialStore.listRotated()`). Never returns `storedKid` —
   * exposing it would let a hostile script fingerprint SESSION_SECRET
   * rotations across requests.
   */
  async status(sourceId: string): Promise<ObserverKeyStatus> {
    const row = await databaseService.meshcoreObserverKeys.getBySourceId(sourceId);
    if (!row) {
      return {
        stored: false,
        publicKey: null,
        origin: null,
        updatedAt: null,
        keyRotated: false,
        canStore: this._capability.canStore,
        reason: this._capability.reason ?? null,
      };
    }

    let keyRotated: boolean;
    try {
      const env = JSON.parse(row.encryptedPrivateKey) as StoredEnvelope;
      keyRotated = env.v !== KDF_VERSION || env.kid !== this.currentKid;
    } catch {
      keyRotated = true;
    }

    const origin: 'device' | 'manual' | null =
      row.keyOrigin === 'device' || row.keyOrigin === 'manual' ? row.keyOrigin : null;

    return {
      stored: true,
      publicKey: row.publicKey ?? null,
      origin,
      updatedAt: row.updatedAt,
      keyRotated,
      canStore: this._capability.canStore,
      reason: this._capability.reason ?? null,
    };
  }
}

/**
 * HKDF-SHA256 wrapper returning a Buffer. We use a stable zero salt because
 * the IKM (SESSION_SECRET) is itself high-entropy and we need the derivation
 * to be deterministic — persisting a random salt in the DB would re-introduce
 * the key-rotation problem we're trying to detect.
 */
function hkdfBytes(ikm: Buffer, info: string, length: number): Buffer {
  const salt = Buffer.alloc(32);
  return Buffer.from(crypto.hkdfSync('sha256', ikm, salt, info, length));
}

// ---------------------------------------------------------------------------
// Module-level singleton — lazily constructed so tests can inject their own
// secret via `setMeshCoreObserverKeyStoreForTesting`. The runtime path
// initializes from the environment config on first access.
// ---------------------------------------------------------------------------

let singleton: MeshCoreObserverKeyStore | null = null;

export function getMeshCoreObserverKeyStore(): MeshCoreObserverKeyStore {
  if (!singleton) {
    const { sessionSecret, sessionSecretProvided } = getEnvironmentConfig();
    singleton = new MeshCoreObserverKeyStore(sessionSecret, sessionSecretProvided);
  }
  return singleton;
}

/** Test hook: replace the singleton with a custom instance, or pass null
 *  to force re-initialization on the next access. */
export function setMeshCoreObserverKeyStoreForTesting(store: MeshCoreObserverKeyStore | null): void {
  singleton = store;
}
