/**
 * MeshCoreObserverCredentialStore
 *
 * Encrypts and persists a MeshCore source's STATIC MQTT broker password for
 * the Analyzer Observer (issue #4595). Some regional Analyzer brokers — e.g.
 * meshcoretel.ru — do not verify the Ed25519-signed token that the
 * `v1_{PUBLIC_KEY}` scheme produces; they authenticate with a plain MQTT
 * username/password instead.
 *
 * Structural copy of `MeshCoreObserverKeyStore` / `MeshCoreCredentialStore`:
 * AES-256-GCM with an HKDF-derived key from `SESSION_SECRET`, with an
 * envelope `kid` so a rotated secret is detected (`key_rotated`) rather than
 * silently failing with an auth-tag error.
 *
 * KDF info strings are deliberately NEW and distinct from every other store
 * ('source-pki-key-*', 'meshcore-admin-creds-*', 'meshcore-observer-key-*').
 * Reusing one would mean a leaked SESSION_SECRET plus a copy of this table
 * could be decrypted by code that only knows another store's derivation;
 * distinct info strings key-separate the stores even though they share one
 * secret.
 *
 * MULTI-BROKER (#5014 Phase 1): the schema is untouched — still one row per
 * source, `meshcore_observer_credentials(sourceId, username, encryptedPassword)`.
 * What changed is the shape of the AEAD *plaintext*: it is now a versioned
 * JSON document (`StoredCredentialDoc`) holding every broker's credential
 * plus the pre-#5014 "legacy" single credential, instead of a bare password
 * string. One envelope, one `kid`, one rotation story, regardless of how many
 * brokers a source publishes to. See `decodeDoc` for the v1/v2 discriminator
 * and §4 of `docs/internal/dev-notes/MESHMAPPER_OBSERVER_PHASE1_SPEC.md` for
 * the full trade-off against a per-broker table + migration (rejected).
 *
 * WHERE THE SECRET LIVES (security summary):
 *   - `meshcore_observer_credentials.encryptedPassword` — AES-256-GCM
 *     envelope JSON. Nothing else in the process, the DB, or `sources.config`
 *     ever holds a password (legacy or per-broker).
 *   - It is decrypted in exactly ONE place: `MeshCoreObserverPublisher`, to
 *     build the MQTT CONNECT packet. No route ever reads it.
 *   - `username` is stored in the CLEAR alongside it. It is not a secret (a
 *     non-TLS broker receives it in plaintext regardless) and the UI needs it
 *     to show which account is configured. It holds the legacy username when
 *     a legacy entry exists, otherwise the username of the
 *     lexicographically-first broker entry (see `computeClearUsername`). It
 *     is display-only and is never used to authenticate a per-broker
 *     connection — `loadForBroker` reads the real per-broker username out of
 *     the decrypted document.
 *
 * Threat model (same as the sibling stores):
 *   - Defends against a DB-file-only exfil (someone grabs `meshmonitor.db`
 *     without the host environment).
 *   - Does NOT defend against host compromise. Anyone running code on the
 *     host can read SESSION_SECRET and the DB.
 *
 * Capability gating: when SESSION_SECRET was NOT explicitly configured
 * (auto-generated by the environment loader), `canStore` is false — an
 * ephemeral key would lose the stored password on every restart.
 */
import crypto from 'node:crypto';
import databaseService from '../../services/database.js';
import { logger } from '../../utils/logger.js';
import { getEnvironmentConfig } from '../config/environment.js';

/** KDF version stamped into each envelope. Bump if the HKDF info-strings or
 *  AEAD parameters ever change so old rows route through key_rotated. */
const KDF_VERSION = 1;
const KDF_INFO_AEAD = 'meshcore-observer-cred-aead-v1';
const KDF_INFO_FINGERPRINT = 'meshcore-observer-cred-fingerprint-v1';

/** Hard cap on a stored password, matching the MQTT CONNECT field limit. */
export const OBSERVER_PASSWORD_MAX_LENGTH = 512;
/** Hard cap on a stored username; matches the MySQL column width. */
export const OBSERVER_USERNAME_MAX_LENGTH = 255;
/**
 * Max distinct broker credentials per source (#5014). Matches
 * `MAX_OBSERVER_BROKERS` in `sourceRoutes.ts` validation — the two are chosen
 * together (see spec §2.5): a source can never be *configured* with more
 * brokers than it can have credentials for.
 */
export const OBSERVER_MAX_BROKER_CREDENTIALS = 8;

interface StoredEnvelope {
  v: number;
  kid: string;
  iv: string;
  ct: string;
  tag: string;
}

/**
 * The AEAD plaintext shape (#5014). `brokerKey` is `observerBrokerKey(url)`
 * (case-insensitive normalized URL) — see `meshcoreConfig.ts`. This module
 * never derives or validates a `brokerKey`; it is an opaque string handed in
 * by the caller (route or publisher), by design (this store must not import
 * `meshcoreConfig.ts`).
 */
interface StoredCredentialDoc {
  v: 2;
  /** brokerKey -> credential. */
  brokers: Record<string, { username: string; password: string }>;
  /**
   * The pre-#5014 single credential, carried forward verbatim when a v1
   * document is upgraded in place (see `decodeDoc`). Read by `load()` and by
   * the publisher's legacy-broker fallback (`resolveBrokerCredential`, which
   * lives in `meshcoreObserverPublisher.ts`, NOT in this store — this store
   * has no notion of which broker "is" the legacy one).
   */
  legacy?: { username: string; password: string };
}

export interface ObserverCredentialCapability {
  canStore: boolean;
  /** Human-readable explanation when canStore=false, surfaced to the UI. */
  reason?: string;
}

export type ObserverCredentialLoadResult =
  | { kind: 'none' }
  | { kind: 'ok'; username: string; password: string }
  | { kind: 'key_rotated'; storedKid: string };

export interface ObserverCredentialStatus {
  stored: boolean;
  /** NOT secret — displayed in the UI. The password is never returned. */
  username: string | null;
  updatedAt: number | null;
  /** True when an envelope exists but was encrypted under a different SESSION_SECRET. */
  keyRotated: boolean;
  canStore: boolean;
  reason: string | null;
  /**
   * Non-secret per-broker enumeration (#5014) — same pairs as `listBrokers()`.
   * Present only when the decrypted document actually has at least one
   * broker entry; a pre-#5014 legacy-only row (or a not-found / key-rotated
   * row) omits this field entirely rather than sending `brokers: []`, so
   * `Object.keys(status)` is unchanged for every caller that predates
   * multi-broker credentials.
   */
  brokers?: Array<{ brokerKey: string; username: string }>;
}

/** Result of decrypting and decoding a source's stored document. Internal —
 *  every public method is a thin projection over this. */
type DecodedDocResult =
  | { kind: 'none' }
  | { kind: 'key_rotated'; storedKid: string; row: { username: string; updatedAt: number } }
  | { kind: 'ok'; doc: StoredCredentialDoc; row: { username: string; updatedAt: number } };

export class MeshCoreObserverCredentialStore {
  private readonly aeadKey: Buffer;
  private readonly currentKid: string;
  private readonly _capability: ObserverCredentialCapability;

  constructor(sessionSecret: string, sessionSecretProvided: boolean) {
    this._capability = sessionSecretProvided
      ? { canStore: true }
      : {
          canStore: false,
          reason:
            'SESSION_SECRET was not configured; an auto-generated value is in use. ' +
            'A stored Analyzer Observer broker password would be unrecoverable on every restart. ' +
            'Set SESSION_SECRET=$(openssl rand -hex 32) to enable static-credential observer auth.',
        };
    const ikm = Buffer.from(sessionSecret, 'utf8');
    this.aeadKey = hkdfBytes(ikm, KDF_INFO_AEAD, 32);
    this.currentKid = hkdfBytes(ikm, KDF_INFO_FINGERPRINT, 4).toString('hex');
  }

  get capability(): ObserverCredentialCapability {
    return this._capability;
  }

  /** Exposed mostly for tests; consumers should react to `key_rotated`. */
  get currentFingerprint(): string {
    return this.currentKid;
  }

  /**
   * Encrypt and persist the LEGACY broker password for a source, alongside
   * the clear `username`. Writes a v2 document whose `legacy` is the
   * supplied pair, PRESERVING any existing `brokers` map (read-modify-write —
   * see the concurrency note on `storeForBroker`). Throws when SESSION_SECRET
   * is auto-generated — callers must check `capability` first.
   */
  async store(sourceId: string, username: string, password: string): Promise<void> {
    if (!this._capability.canStore) {
      throw new Error('Cannot persist Analyzer Observer broker password: SESSION_SECRET is auto-generated');
    }
    const existing = await this.readDoc(sourceId);
    // A row we cannot decrypt (key_rotated) has an unrecoverable brokers map
    // regardless of what we do here, so there is nothing to preserve; start
    // fresh rather than blocking the operator's write.
    const brokers = existing.kind === 'ok' ? existing.doc.brokers : {};
    const doc: StoredCredentialDoc = { v: 2, brokers, legacy: { username, password } };
    await this.persistDoc(sourceId, doc);
  }

  /**
   * Load + decrypt the stored LEGACY credential for a source. Returns one of:
   *   - `{ kind: 'none' }` when nothing is saved, or a document exists but
   *     has no `legacy` entry (e.g. only per-broker credentials).
   *   - `{ kind: 'ok', username, password }` on success.
   *   - `{ kind: 'key_rotated', storedKid }` when the envelope was encrypted
   *     with a different SESSION_SECRET.
   *
   * For any row written before #5014 this is bit-for-bit today's behaviour:
   * such a row decodes to a document whose `legacy` is exactly that row's
   * username/password (see `decodeDoc`).
   */
  async load(sourceId: string): Promise<ObserverCredentialLoadResult> {
    const result = await this.readDoc(sourceId);
    if (result.kind === 'none') return { kind: 'none' };
    if (result.kind === 'key_rotated') return { kind: 'key_rotated', storedKid: result.storedKid };
    if (!result.doc.legacy) return { kind: 'none' };
    return { kind: 'ok', username: result.doc.legacy.username, password: result.doc.legacy.password };
  }

  /**
   * Read-modify-write one broker's entry (#5014). Throws when
   * `capability.canStore` is false (same condition as `store()`), or when
   * adding a *new* distinct broker would exceed `OBSERVER_MAX_BROKER_CREDENTIALS`
   * (updating an already-present `brokerKey` never counts against the cap).
   *
   * CONCURRENCY (must stay a comment — see spec §4.4): this is a
   * read-decrypt-modify-encrypt-write cycle over ONE row. Two concurrent
   * writes to *different* brokers on the same source can race and lose one
   * update (last write wins on the whole document, not just the touched
   * broker). Accepted for v1: both `storeForBroker` and `clearForBroker` are
   * operator-driven admin-route calls against a single source, and the loss
   * is recoverable by re-entering the credential. If a future UI ever
   * batch-saves N brokers in one gesture, it MUST serialize those PUTs.
   */
  async storeForBroker(sourceId: string, brokerKey: string, username: string, password: string): Promise<void> {
    if (!this._capability.canStore) {
      throw new Error('Cannot persist Analyzer Observer broker password: SESSION_SECRET is auto-generated');
    }
    const existing = await this.readDoc(sourceId);
    // See store()'s comment: a key-rotated row's brokers map is already
    // unrecoverable, so we start fresh rather than blocking the write.
    const doc: StoredCredentialDoc =
      existing.kind === 'ok'
        ? { v: 2, brokers: { ...existing.doc.brokers }, legacy: existing.doc.legacy }
        : { v: 2, brokers: {} };

    if (!(brokerKey in doc.brokers) && Object.keys(doc.brokers).length >= OBSERVER_MAX_BROKER_CREDENTIALS) {
      throw new Error(
        `Cannot store credentials for broker "${brokerKey}": the maximum of ` +
          `${OBSERVER_MAX_BROKER_CREDENTIALS} distinct broker credentials has been reached`,
      );
    }

    doc.brokers[brokerKey] = { username, password };
    await this.persistDoc(sourceId, doc);
  }

  /**
   * This broker's credential only. NEVER falls back to `legacy` — that
   * fallback is a publisher-level policy decision (`resolveBrokerCredential`
   * in `meshcoreObserverPublisher.ts`), not a store-level one, so that a
   * non-legacy broker can never observe the legacy credential.
   */
  async loadForBroker(sourceId: string, brokerKey: string): Promise<ObserverCredentialLoadResult> {
    const result = await this.readDoc(sourceId);
    if (result.kind === 'none') return { kind: 'none' };
    if (result.kind === 'key_rotated') return { kind: 'key_rotated', storedKid: result.storedKid };
    const entry = result.doc.brokers[brokerKey];
    if (!entry) return { kind: 'none' };
    return { kind: 'ok', username: entry.username, password: entry.password };
  }

  /**
   * Remove one broker's entry (#5014). No-op when absent — including when no
   * row exists at all, or when the row exists but cannot be decrypted
   * (key_rotated: see the concurrency/read-modify-write comment on
   * `storeForBroker`; we refuse to blindly rewrite a document we cannot
   * read). Deletes the whole row once the resulting document has neither
   * broker entries nor a legacy entry, matching `clear()`'s row-deletion
   * behaviour instead of leaving an empty husk envelope behind.
   */
  async clearForBroker(sourceId: string, brokerKey: string): Promise<void> {
    const existing = await this.readDoc(sourceId);
    if (existing.kind !== 'ok' || !(brokerKey in existing.doc.brokers)) {
      return;
    }
    const brokers = { ...existing.doc.brokers };
    delete brokers[brokerKey];
    const doc: StoredCredentialDoc = { v: 2, brokers, legacy: existing.doc.legacy };
    if (Object.keys(doc.brokers).length === 0 && !doc.legacy) {
      await databaseService.meshcoreObserverCredentials.deleteBySourceId(sourceId);
      return;
    }
    await this.persistDoc(sourceId, doc);
  }

  /**
   * Non-secret enumeration for the UI (#5014). NEVER returns a password —
   * only `{ brokerKey, username }` pairs. Returns `[]` when there is no row,
   * or the row cannot be decrypted (key_rotated): the caller learns about
   * rotation from `status()`, not from an empty broker list.
   */
  async listBrokers(sourceId: string): Promise<Array<{ brokerKey: string; username: string }>> {
    const result = await this.readDoc(sourceId);
    if (result.kind !== 'ok') return [];
    return Object.entries(result.doc.brokers).map(([brokerKey, cred]) => ({ brokerKey, username: cred.username }));
  }

  /** Clear any stored credentials for a source. No-op if none exists. */
  async clear(sourceId: string): Promise<void> {
    await databaseService.meshcoreObserverCredentials.deleteBySourceId(sourceId);
  }

  /**
   * Report status. Compares the envelope's `v`/`kid` against the current
   * fingerprint and, when it matches, decrypts to populate the additive
   * `brokers` field (#5014) — see that field's doc comment for the exact
   * omission rule that keeps this back-compatible. Never returns
   * `storedKid` — exposing it would let a hostile script fingerprint
   * SESSION_SECRET rotations across requests — and NEVER returns a password.
   */
  async status(sourceId: string): Promise<ObserverCredentialStatus> {
    const result = await this.readDoc(sourceId);

    if (result.kind === 'none') {
      return {
        stored: false,
        username: null,
        updatedAt: null,
        keyRotated: false,
        canStore: this._capability.canStore,
        reason: this._capability.reason ?? null,
      };
    }

    if (result.kind === 'key_rotated') {
      return {
        stored: true,
        username: result.row.username,
        updatedAt: result.row.updatedAt,
        keyRotated: true,
        canStore: this._capability.canStore,
        reason: this._capability.reason ?? null,
      };
    }

    const brokerEntries = Object.entries(result.doc.brokers).map(([brokerKey, cred]) => ({
      brokerKey,
      username: cred.username,
    }));

    return {
      stored: true,
      username: result.row.username,
      updatedAt: result.row.updatedAt,
      keyRotated: false,
      canStore: this._capability.canStore,
      reason: this._capability.reason ?? null,
      ...(brokerEntries.length > 0 ? { brokers: brokerEntries } : {}),
    };
  }

  /**
   * Fetch, decrypt and decode the stored document for a source. The single
   * place every public read/write path goes through, so the envelope
   * parsing / kid-matching / decrypt-failure handling exists exactly once.
   * Never throws.
   */
  private async readDoc(sourceId: string): Promise<DecodedDocResult> {
    const row = await databaseService.meshcoreObserverCredentials.getBySourceId(sourceId);
    if (!row) return { kind: 'none' };

    let env: StoredEnvelope;
    try {
      env = JSON.parse(row.encryptedPassword) as StoredEnvelope;
    } catch {
      logger.warn(
        `[MeshCoreObserverCredentialStore] Malformed envelope for ${sourceId}; treating as rotated`,
      );
      return { kind: 'key_rotated', storedKid: '?', row: { username: row.username, updatedAt: row.updatedAt } };
    }
    if (env.v !== KDF_VERSION || env.kid !== this.currentKid) {
      return {
        kind: 'key_rotated',
        storedKid: env.kid ?? '?',
        row: { username: row.username, updatedAt: row.updatedAt },
      };
    }
    try {
      const decipher = crypto.createDecipheriv('aes-256-gcm', this.aeadKey, Buffer.from(env.iv, 'hex'));
      decipher.setAuthTag(Buffer.from(env.tag, 'hex'));
      const pt = Buffer.concat([decipher.update(Buffer.from(env.ct, 'hex')), decipher.final()]).toString('utf8');
      const doc = decodeDoc(pt, row.username);
      return { kind: 'ok', doc, row: { username: row.username, updatedAt: row.updatedAt } };
    } catch (err) {
      // kid matched but decrypt failed — upgrade hazard or row corruption.
      // Treat as rotated so the operator re-enters rather than the publisher
      // silently proceeding with a broken credential.
      logger.warn(
        `[MeshCoreObserverCredentialStore] Decrypt failed for ${sourceId} despite matching kid: ${(err as Error).message}`,
      );
      return { kind: 'key_rotated', storedKid: env.kid, row: { username: row.username, updatedAt: row.updatedAt } };
    }
  }

  /** Encrypt `doc` and upsert it, deriving the clear `username` column via
   *  `computeClearUsername`. The one write path every mutator funnels through. */
  private async persistDoc(sourceId: string, doc: StoredCredentialDoc): Promise<void> {
    const iv = crypto.randomBytes(12);
    const cipher = crypto.createCipheriv('aes-256-gcm', this.aeadKey, iv);
    const ct = Buffer.concat([cipher.update(Buffer.from(JSON.stringify(doc), 'utf8')), cipher.final()]);
    const tag = cipher.getAuthTag();
    const envelope: StoredEnvelope = {
      v: KDF_VERSION,
      kid: this.currentKid,
      iv: iv.toString('hex'),
      ct: ct.toString('hex'),
      tag: tag.toString('hex'),
    };
    await databaseService.meshcoreObserverCredentials.upsert(
      sourceId,
      computeClearUsername(doc),
      JSON.stringify(envelope),
    );
  }
}

/**
 * HKDF-SHA256 wrapper returning a Buffer. Stable zero salt because the IKM
 * (SESSION_SECRET) is itself high-entropy and the derivation must be
 * deterministic — persisting a random salt would re-introduce the
 * key-rotation problem we are trying to detect.
 */
function hkdfBytes(ikm: Buffer, info: string, length: number): Buffer {
  const salt = Buffer.alloc(32);
  return Buffer.from(crypto.hkdfSync('sha256', ikm, salt, info, length));
}

/**
 * Decode the AEAD plaintext into a `StoredCredentialDoc` (#5014).
 *
 * ```
 * try p = JSON.parse(plaintext)
 * if (p && typeof p === 'object' && !Array.isArray(p) && p.v === 2
 *     && p.brokers && typeof p.brokers === 'object')
 *     -> v2 document, used as-is
 * else
 *     -> v1: wrap the plaintext (the bare legacy password) as
 *        { v: 2, brokers: {}, legacy: { username: clearUsername, password: plaintext } }
 * ```
 *
 * `clearUsername` is the row's clear `username` column, which — for a v1 row
 * — IS the legacy username (that column has held exactly the legacy username
 * since before #5014).
 *
 * MISPARSE CAVEAT (accepted, documented per spec §4.2): a v1 password that
 * happens to be *exactly* a JSON object shaped like `{"v":2,"brokers":{...}}`
 * would be misread as a v2 document instead of a literal password. This is
 * accepted as negligible-probability: the alternative (a length-prefixed or
 * otherwise self-describing container) would require rewriting every
 * existing row to migrate, which is exactly the migration this design set
 * out to avoid.
 */
function decodeDoc(plaintext: string, clearUsername: string): StoredCredentialDoc {
  try {
    const parsed: unknown = JSON.parse(plaintext);
    if (
      parsed !== null &&
      typeof parsed === 'object' &&
      !Array.isArray(parsed) &&
      (parsed as Record<string, unknown>).v === 2 &&
      typeof (parsed as Record<string, unknown>).brokers === 'object' &&
      (parsed as Record<string, unknown>).brokers !== null
    ) {
      return parsed as StoredCredentialDoc;
    }
  } catch {
    // Not JSON at all — definitely a v1 plaintext password. Fall through.
  }
  return { v: 2, brokers: {}, legacy: { username: clearUsername, password: plaintext } };
}

/**
 * Derive the clear `username` column value for a document (#5014). That
 * column is display-only (see the file-header security summary) and holds:
 *   - the legacy username, when a `legacy` entry exists (this is also what
 *     keeps every pre-#5014 row's clear username byte-for-byte unchanged,
 *     since `store()` always sets `legacy`);
 *   - otherwise, the username of the lexicographically-first broker entry,
 *     so a source with only per-broker credentials still shows *something*
 *     recognizable in the UI;
 *   - otherwise (a document with neither) the empty string — this path is
 *     unreachable from any public method today, since `clearForBroker`
 *     deletes the row instead of persisting a fully-empty document.
 */
function computeClearUsername(doc: StoredCredentialDoc): string {
  if (doc.legacy) return doc.legacy.username;
  const keys = Object.keys(doc.brokers).sort();
  return keys.length > 0 ? doc.brokers[keys[0]].username : '';
}

// ---------------------------------------------------------------------------
// Module-level singleton — lazily constructed so tests can inject their own
// secret via `setMeshCoreObserverCredentialStoreForTesting`.
// ---------------------------------------------------------------------------

let singleton: MeshCoreObserverCredentialStore | null = null;

export function getMeshCoreObserverCredentialStore(): MeshCoreObserverCredentialStore {
  if (!singleton) {
    const { sessionSecret, sessionSecretProvided } = getEnvironmentConfig();
    singleton = new MeshCoreObserverCredentialStore(sessionSecret, sessionSecretProvided);
  }
  return singleton;
}

/** Test hook: replace the singleton with a custom instance, or pass null
 *  to force re-initialization on the next access. */
export function setMeshCoreObserverCredentialStoreForTesting(
  store: MeshCoreObserverCredentialStore | null,
): void {
  singleton = store;
}
