/**
 * MeshCoreObserverCredentialStore
 *
 * Encrypts and persists a MeshCore source's STATIC MQTT broker password for
 * the Analyzer Observer (issue #4595). Some regional Analyzer brokers — e.g.
 * meshcoretel.ru — do not verify the Ed25519-signed token that the
 * `v1_{PUBLIC_KEY}` scheme produces; they authenticate with a plain MQTT
 * username/password instead.
 *
 * Structural copy of `MeshCoreObserverKeyStore` / `MeshCoreCredentialStore`:
 * AES-256-GCM with an HKDF-derived key from `SESSION_SECRET`, with an
 * envelope `kid` so a rotated secret is detected (`key_rotated`) rather than
 * silently failing with an auth-tag error.
 *
 * KDF info strings are deliberately NEW and distinct from every other store
 * ('source-pki-key-*', 'meshcore-admin-creds-*', 'meshcore-observer-key-*').
 * Reusing one would mean a leaked SESSION_SECRET plus a copy of this table
 * could be decrypted by code that only knows another store's derivation;
 * distinct info strings key-separate the stores even though they share one
 * secret.
 *
 * WHERE THE SECRET LIVES (security summary):
 *   - `meshcore_observer_credentials.encryptedPassword` — AES-256-GCM
 *     envelope JSON. Nothing else in the process, the DB, or `sources.config`
 *     ever holds the password.
 *   - It is decrypted in exactly ONE place: `MeshCoreObserverPublisher`, to
 *     build the MQTT CONNECT packet. No route ever reads it.
 *   - `username` is stored in the CLEAR alongside it. It is not a secret (a
 *     non-TLS broker receives it in plaintext regardless) and the UI needs it
 *     to show which account is configured.
 *
 * Threat model (same as the sibling stores):
 *   - Defends against a DB-file-only exfil (someone grabs `meshmonitor.db`
 *     without the host environment).
 *   - Does NOT defend against host compromise. Anyone running code on the
 *     host can read SESSION_SECRET and the DB.
 *
 * Capability gating: when SESSION_SECRET was NOT explicitly configured
 * (auto-generated by the environment loader), `canStore` is false — an
 * ephemeral key would lose the stored password on every restart.
 */
import crypto from 'node:crypto';
import databaseService from '../../services/database.js';
import { logger } from '../../utils/logger.js';
import { getEnvironmentConfig } from '../config/environment.js';

/** KDF version stamped into each envelope. Bump if the HKDF info-strings or
 *  AEAD parameters ever change so old rows route through key_rotated. */
const KDF_VERSION = 1;
const KDF_INFO_AEAD = 'meshcore-observer-cred-aead-v1';
const KDF_INFO_FINGERPRINT = 'meshcore-observer-cred-fingerprint-v1';

/** Hard cap on a stored password, matching the MQTT CONNECT field limit. */
export const OBSERVER_PASSWORD_MAX_LENGTH = 512;
/** Hard cap on a stored username; matches the MySQL column width. */
export const OBSERVER_USERNAME_MAX_LENGTH = 255;

interface StoredEnvelope {
  v: number;
  kid: string;
  iv: string;
  ct: string;
  tag: string;
}

export interface ObserverCredentialCapability {
  canStore: boolean;
  /** Human-readable explanation when canStore=false, surfaced to the UI. */
  reason?: string;
}

export type ObserverCredentialLoadResult =
  | { kind: 'none' }
  | { kind: 'ok'; username: string; password: string }
  | { kind: 'key_rotated'; storedKid: string };

export interface ObserverCredentialStatus {
  stored: boolean;
  /** NOT secret — displayed in the UI. The password is never returned. */
  username: string | null;
  updatedAt: number | null;
  /** True when an envelope exists but was encrypted under a different SESSION_SECRET. */
  keyRotated: boolean;
  canStore: boolean;
  reason: string | null;
}

export class MeshCoreObserverCredentialStore {
  private readonly aeadKey: Buffer;
  private readonly currentKid: string;
  private readonly _capability: ObserverCredentialCapability;

  constructor(sessionSecret: string, sessionSecretProvided: boolean) {
    this._capability = sessionSecretProvided
      ? { canStore: true }
      : {
          canStore: false,
          reason:
            'SESSION_SECRET was not configured; an auto-generated value is in use. ' +
            'A stored Analyzer Observer broker password would be unrecoverable on every restart. ' +
            'Set SESSION_SECRET=$(openssl rand -hex 32) to enable static-credential observer auth.',
        };
    const ikm = Buffer.from(sessionSecret, 'utf8');
    this.aeadKey = hkdfBytes(ikm, KDF_INFO_AEAD, 32);
    this.currentKid = hkdfBytes(ikm, KDF_INFO_FINGERPRINT, 4).toString('hex');
  }

  get capability(): ObserverCredentialCapability {
    return this._capability;
  }

  /** Exposed mostly for tests; consumers should react to `key_rotated`. */
  get currentFingerprint(): string {
    return this.currentKid;
  }

  /**
   * Encrypt and persist the broker password for a source, alongside the clear
   * `username`. Throws when SESSION_SECRET is auto-generated — callers must
   * check `capability` first.
   */
  async store(sourceId: string, username: string, password: string): Promise<void> {
    if (!this._capability.canStore) {
      throw new Error('Cannot persist Analyzer Observer broker password: SESSION_SECRET is auto-generated');
    }
    const iv = crypto.randomBytes(12);
    const cipher = crypto.createCipheriv('aes-256-gcm', this.aeadKey, iv);
    const ct = Buffer.concat([cipher.update(Buffer.from(password, 'utf8')), cipher.final()]);
    const tag = cipher.getAuthTag();
    const envelope: StoredEnvelope = {
      v: KDF_VERSION,
      kid: this.currentKid,
      iv: iv.toString('hex'),
      ct: ct.toString('hex'),
      tag: tag.toString('hex'),
    };
    await databaseService.meshcoreObserverCredentials.upsert(sourceId, username, JSON.stringify(envelope));
  }

  /**
   * Load + decrypt the stored credentials for a source. Returns one of:
   *   - `{ kind: 'none' }` when nothing is saved.
   *   - `{ kind: 'ok', username, password }` on success.
   *   - `{ kind: 'key_rotated', storedKid }` when the envelope was encrypted
   *     with a different SESSION_SECRET.
   */
  async load(sourceId: string): Promise<ObserverCredentialLoadResult> {
    const row = await databaseService.meshcoreObserverCredentials.getBySourceId(sourceId);
    if (!row) return { kind: 'none' };

    let env: StoredEnvelope;
    try {
      env = JSON.parse(row.encryptedPassword) as StoredEnvelope;
    } catch {
      logger.warn(
        `[MeshCoreObserverCredentialStore] Malformed envelope for ${sourceId}; treating as rotated`,
      );
      return { kind: 'key_rotated', storedKid: '?' };
    }
    if (env.v !== KDF_VERSION || env.kid !== this.currentKid) {
      return { kind: 'key_rotated', storedKid: env.kid ?? '?' };
    }
    try {
      const decipher = crypto.createDecipheriv('aes-256-gcm', this.aeadKey, Buffer.from(env.iv, 'hex'));
      decipher.setAuthTag(Buffer.from(env.tag, 'hex'));
      const pt = Buffer.concat([decipher.update(Buffer.from(env.ct, 'hex')), decipher.final()]);
      return { kind: 'ok', username: row.username, password: pt.toString('utf8') };
    } catch (err) {
      // kid matched but decrypt failed — upgrade hazard or row corruption.
      // Treat as rotated so the operator re-enters rather than the publisher
      // silently proceeding with a broken credential.
      logger.warn(
        `[MeshCoreObserverCredentialStore] Decrypt failed for ${sourceId} despite matching kid: ${(err as Error).message}`,
      );
      return { kind: 'key_rotated', storedKid: env.kid };
    }
  }

  /** Clear any stored credentials for a source. No-op if none exists. */
  async clear(sourceId: string): Promise<void> {
    await databaseService.meshcoreObserverCredentials.deleteBySourceId(sourceId);
  }

  /**
   * Report status without attempting decryption: compares the envelope's
   * `v`/`kid` against the current fingerprint only. Never returns `storedKid`
   * — exposing it would let a hostile script fingerprint SESSION_SECRET
   * rotations across requests — and NEVER returns the password.
   */
  async status(sourceId: string): Promise<ObserverCredentialStatus> {
    const row = await databaseService.meshcoreObserverCredentials.getBySourceId(sourceId);
    if (!row) {
      return {
        stored: false,
        username: null,
        updatedAt: null,
        keyRotated: false,
        canStore: this._capability.canStore,
        reason: this._capability.reason ?? null,
      };
    }

    let keyRotated: boolean;
    try {
      const env = JSON.parse(row.encryptedPassword) as StoredEnvelope;
      keyRotated = env.v !== KDF_VERSION || env.kid !== this.currentKid;
    } catch {
      keyRotated = true;
    }

    return {
      stored: true,
      username: row.username,
      updatedAt: row.updatedAt,
      keyRotated,
      canStore: this._capability.canStore,
      reason: this._capability.reason ?? null,
    };
  }
}

/**
 * HKDF-SHA256 wrapper returning a Buffer. Stable zero salt because the IKM
 * (SESSION_SECRET) is itself high-entropy and the derivation must be
 * deterministic — persisting a random salt would re-introduce the
 * key-rotation problem we are trying to detect.
 */
function hkdfBytes(ikm: Buffer, info: string, length: number): Buffer {
  const salt = Buffer.alloc(32);
  return Buffer.from(crypto.hkdfSync('sha256', ikm, salt, info, length));
}

// ---------------------------------------------------------------------------
// Module-level singleton — lazily constructed so tests can inject their own
// secret via `setMeshCoreObserverCredentialStoreForTesting`.
// ---------------------------------------------------------------------------

let singleton: MeshCoreObserverCredentialStore | null = null;

export function getMeshCoreObserverCredentialStore(): MeshCoreObserverCredentialStore {
  if (!singleton) {
    const { sessionSecret, sessionSecretProvided } = getEnvironmentConfig();
    singleton = new MeshCoreObserverCredentialStore(sessionSecret, sessionSecretProvided);
  }
  return singleton;
}

/** Test hook: replace the singleton with a custom instance, or pass null
 *  to force re-initialization on the next access. */
export function setMeshCoreObserverCredentialStoreForTesting(
  store: MeshCoreObserverCredentialStore | null,
): void {
  singleton = store;
}
