# Default values for meshmonitor

# Image configuration
image:
  repository: ghcr.io/yeraze/meshmonitor
  pullPolicy: IfNotPresent
  tag: "latest"

# Number of replicas
replicaCount: 1

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3001

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: meshmonitor.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
    # - secretName: meshmonitor-tls
    #   hosts:
    #     - meshmonitor.local

# Environment variables
# Required configuration for Meshtastic node connection
env:
  # IP address of your Meshtastic node (REQUIRED)
  meshtasticNodeIp: "192.168.1.100"

  # Enable HTTPS connection to node (REQUIRED)
  meshtasticUseTls: "false"

  # Environment mode (optional)
  nodeEnv: "production"

  # Server port - should match service.targetPort (optional)
  port: "3001"

  # Runtime base URL path for subfolder deployment (optional)
  # Example: "/meshmonitor" for hosting at https://example.com/meshmonitor/
  baseUrl: ""

# Persistent storage for SQLite database
persistence:
  enabled: true
  # storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
  # existingClaim: ""

# Resource limits and requests
resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 250m
  #   memory: 256Mi

# Node selector for pod assignment
nodeSelector: {}

# Tolerations for pod assignment
tolerations: []

# Affinity for pod assignment
affinity: {}

# Security context
podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
