/**
 * Migration 174 — PostgreSQL / MySQL container behaviour.
 *
 * PostgreSQL: a sequence left behind by an explicit-id restore is advanced,
 * and a re-run is a no-op. MySQL: the runner is a no-op, and InnoDB
 * AUTO_INCREMENT already advances on explicit-id inserts (the reason it can
 * be). Each backend runs in its own isolated database; skips are silent, so
 * confirm coverage via `numPendingTests` in the JSON reporter.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import pg from 'pg';
import mysql from 'mysql2/promise';
import { runMigration174Postgres, runMigration174Mysql } from './174_reset_postgres_sequences.js';
import {
  postgresAvailable,
  mysqlAvailable,
  createIsolatedPostgresDatabase,
  createIsolatedMysqlDatabase,
} from '../../db/repositories/test-utils.js';

describe.skipIf(!postgresAvailable)('migration 174 — PostgreSQL (container)', () => {
  let pool: pg.Pool;
  let cleanup: (() => Promise<void>) | undefined;

  beforeAll(async () => {
    ({ pool, cleanup } = await createIsolatedPostgresDatabase('mig174'));
    await pool.query('CREATE TABLE audit_log (id SERIAL PRIMARY KEY, action TEXT)');
    await pool.query('CREATE TABLE telemetry (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v TEXT)');
    await pool.query('CREATE TABLE untouched (id SERIAL PRIMARY KEY, v TEXT)');
  });

  afterAll(async () => {
    await cleanup?.();
  });

  it('repairs sequences desynced by an explicit-id restore and is idempotent', async () => {
    // What a pre-fix restore left behind: rows with explicit ids, sequences
    // never advanced.
    for (let id = 1; id <= 7; id++) {
      await pool.query(`INSERT INTO audit_log (id, action) VALUES ($1, 'restored')`, [id]);
      await pool.query(`INSERT INTO telemetry (id, v) VALUES ($1, 'restored')`, [id]);
    }
    await expect(pool.query(`INSERT INTO audit_log (action) VALUES ('new')`)).rejects.toThrow(/duplicate key/);

    const client = await pool.connect();
    try {
      await runMigration174Postgres(client);
      await expect(runMigration174Postgres(client)).resolves.toBeUndefined();
    } finally {
      client.release();
    }

    const audit = await pool.query(`INSERT INTO audit_log (action) VALUES ('new') RETURNING id`);
    expect(audit.rows[0].id).toBe(8);
    const tel = await pool.query(`INSERT INTO telemetry (v) VALUES ('new') RETURNING id`);
    expect(Number(tel.rows[0].id)).toBe(8);
    // Empty table untouched: first id is still 1.
    const fresh = await pool.query(`INSERT INTO untouched (v) VALUES ('new') RETURNING id`);
    expect(fresh.rows[0].id).toBe(1);
  });
});

describe.skipIf(!mysqlAvailable)('migration 174 — MySQL (container)', () => {
  let pool: mysql.Pool;
  let cleanup: (() => Promise<void>) | undefined;

  beforeAll(async () => {
    ({ pool, cleanup } = await createIsolatedMysqlDatabase('mig174'));
    await pool.query('CREATE TABLE audit_log (id INT AUTO_INCREMENT PRIMARY KEY, action VARCHAR(32))');
  });

  afterAll(async () => {
    await cleanup?.();
  });

  it('InnoDB AUTO_INCREMENT advances on explicit-id inserts, and the runner is a no-op', async () => {
    // Restore shape: live rows, DELETE, re-insert original ids.
    await pool.query(`INSERT INTO audit_log (action) VALUES ('live'), ('live')`);
    await pool.query('DELETE FROM audit_log');
    for (let id = 1; id <= 7; id++) {
      await pool.query(`INSERT INTO audit_log (id, action) VALUES (?, 'restored')`, [id]);
    }

    await runMigration174Mysql(pool);
    await runMigration174Mysql(pool);

    const [res] = await pool.query(`INSERT INTO audit_log (action) VALUES ('new')`);
    expect((res as mysql.ResultSetHeader).insertId).toBe(8);
  });
});
