/**
 * resetPostgresSequences — PostgreSQL container behaviour.
 *
 * `describe.skipIf(!postgresAvailable)` against localhost:5433 in an isolated
 * database. A silent skip still reports `success: true`; confirm coverage via
 * `numPendingTests` in the JSON reporter (see CLAUDE.md Multi-Database).
 */
import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import pg from 'pg';
import { resetPostgresSequences } from './postgresSequences.js';
import { postgresAvailable, createIsolatedPostgresDatabase } from '../../db/repositories/test-utils.js';

describe.skipIf(!postgresAvailable)('resetPostgresSequences — PostgreSQL (container)', () => {
  let pool: pg.Pool;
  let cleanup: (() => Promise<void>) | undefined;

  beforeAll(async () => {
    ({ pool, cleanup } = await createIsolatedPostgresDatabase('pgseq'));
  });

  afterAll(async () => {
    await cleanup?.();
  });

  beforeEach(async () => {
    await pool.query('DROP TABLE IF EXISTS seq_serial, seq_empty, seq_identity, "SeqMixedCase" CASCADE');
    await pool.query('CREATE TABLE seq_serial (id SERIAL PRIMARY KEY, label TEXT)');
    await pool.query('CREATE TABLE seq_empty (id SERIAL PRIMARY KEY, label TEXT)');
    await pool.query('CREATE TABLE seq_identity (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label TEXT)');
    // Mixed-case table + column: exercises the quote_ident path.
    await pool.query('CREATE TABLE "SeqMixedCase" ("rowId" SERIAL PRIMARY KEY, label TEXT)');
  });

  async function insertWithoutId(table: string, idCol = 'id'): Promise<number> {
    const { rows } = await pool.query(`INSERT INTO ${table} (label) VALUES ('new') RETURNING "${idCol}" AS id`);
    return Number(rows[0].id);
  }

  async function seedExplicitIds(table: string, idCol = 'id', max = 5): Promise<void> {
    for (let id = 1; id <= max; id++) {
      await pool.query(`INSERT INTO ${table} ("${idCol}", label) VALUES ($1, 'old')`, [id]);
    }
  }

  it('advances SERIAL, IDENTITY and quoted-name sequences past explicit ids; leaves empty tables at 1', async () => {
    await seedExplicitIds('seq_serial');
    await seedExplicitIds('seq_identity');
    await seedExplicitIds('"SeqMixedCase"', 'rowId');

    // Unrepaired: the sequence still hands out 1, which collides.
    await expect(insertWithoutId('seq_serial')).rejects.toThrow(/duplicate key/);

    const client = await pool.connect();
    let result;
    try {
      result = await resetPostgresSequences(client);
    } finally {
      client.release();
    }
    // seq_serial's failed insert above burned id 1 (nextval is not rolled
    // back), so its sequence was at next=2 — still behind MAX=5.
    expect(result).toEqual({ checked: 4, advanced: 3, failed: 0 });

    expect(await insertWithoutId('seq_serial')).toBe(6);
    expect(await insertWithoutId('seq_identity')).toBe(6);
    expect(await insertWithoutId('"SeqMixedCase"', 'rowId')).toBe(6);
    // Empty table: first new id is 1, not 2.
    expect(await insertWithoutId('seq_empty')).toBe(1);
  });

  it('is forward-only and idempotent', async () => {
    await seedExplicitIds('seq_serial');
    const client = await pool.connect();
    try {
      await resetPostgresSequences(client);
      expect(await insertWithoutId('seq_serial')).toBe(6);

      // Push the sequence well ahead of MAX (as deletes leave it); a re-run
      // must not pull it back and re-issue ids.
      await pool.query(`SELECT setval(pg_get_serial_sequence('seq_serial', 'id'), 100)`);
      const again = await resetPostgresSequences(client);
      expect(again.advanced).toBe(0);
      expect(await insertWithoutId('seq_serial')).toBe(101);

      // Honour a fresh-style setval(n, false) too: next is n, not n+1.
      await pool.query(`SELECT setval(pg_get_serial_sequence('seq_empty', 'id'), 50, false)`);
      expect((await resetPostgresSequences(client)).advanced).toBe(0);
      expect(await insertWithoutId('seq_empty')).toBe(50);
    } finally {
      client.release();
    }
  });

  it('runs on a client inside a caller transaction; the advance is not undone by ROLLBACK', async () => {
    await seedExplicitIds('seq_serial');
    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      await resetPostgresSequences(client);
      await client.query('ROLLBACK');
    } finally {
      client.release();
    }
    // setval is non-transactional in PostgreSQL, so the advance survives
    // the rollback; that is harmless (forward-only, ids just skip).
    expect(await insertWithoutId('seq_serial')).toBe(6);
  });

  it('reports per-sequence failures through onError instead of throwing', async () => {
    await seedExplicitIds('seq_serial');
    const client = await pool.connect();
    const errors: string[] = [];
    try {
      // A non-integer MAX can't be cast to bigint -> that sequence fails.
      await pool.query('ALTER TABLE seq_empty ALTER COLUMN id DROP DEFAULT');
      await pool.query('ALTER TABLE seq_empty ALTER COLUMN id TYPE NUMERIC USING id::numeric');
      await pool.query(`ALTER TABLE seq_empty ALTER COLUMN id SET DEFAULT nextval('seq_empty_id_seq')`);
      await pool.query(`INSERT INTO seq_empty (id, label) VALUES (1e30, 'huge')`);

      const result = await resetPostgresSequences(client, {
        onError: (seq) => errors.push(seq),
      });
      expect(result.failed).toBe(1);
      expect(errors).toEqual(['public.seq_empty_id_seq']);
      expect(await insertWithoutId('seq_serial')).toBe(6);

      await expect(resetPostgresSequences(client)).rejects.toThrow();
    } finally {
      client.release();
    }
  });
});
